---
title: "Untitled"
output: html_document
date: "2023-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r header}

#####################################################################
# Comparing the effect of mutation accumulation between
# substitution and deletion on the distance from the parent sequence
# You can shorten the run time a bit by decreasing the number 
# of bin counts/bandwidths checked and/or simulations
# By: Stephanie Young <syoung2@sdsu.edu> <syoung49@its.jnj.com>
#####################################################################

```

```{r libraries, message = F}

#=====================================================================
# Loading data and packages -- 
#   assumes "3D_CGR/paper code" is the current working directory
#=====================================================================

source("./data/sequences.R")
source("./R/functions.R")

library(reshape2)
library(msa) # From Bioconductor
library(ape)
library(phangorn)
library(tidyverse)
library(ggplot2)
library(ggdendro)

```

```{r mut_funcs}
 
#=====================================================================
# Mutation functions
#=====================================================================

# Code to perform substitution mutation on a single nucleotide
mtte <- function(nucleotide){
  sample(setdiff(c("A", "T", "C", "G"), nucleotide), 1)
}
mtte.V <- Vectorize(mtte, "nucleotide")


insert_at <- function(a, pos, insert){
  # Give the function a vector of the sequence of nucleotides and it will insert 
  # new nucleotides (insert) at every position (pos)
  if(min(pos) == 1){
    result <- vector("list",2*length(pos))
    result[c(FALSE,TRUE)] <- split(a, cumsum(seq_along(a) %in% (pos)))
    result[c(TRUE,FALSE)] <- insert[order(pos)]
  } else{
    result <- vector("list",2*length(pos)+1)
    result[c(TRUE, FALSE)] <- split(a, cumsum(seq_along(a) %in% (pos)))
    result[c(FALSE, TRUE)] <- insert[order(pos)]
  }
  unlist(result)
}

sample_interval <- function(x, size, interval_length){
  # Sample interval_length contiguous/adjacent elements from x size times.
  # Does not allow overlapping of sampled intervals
  # Does not allow repeat sample of the same interval
  indices <- 1:(length(x) - interval_length + 1)
  sampled_indices <- sample(indices, 1)
  sampled_indices <- sampled_indices : (sampled_indices + interval_length - 1)
  times <- 1
  while(times < size){
    remaining_viable_indices <- setdiff(1:length(x), sampled_indices)
    check <- lead(remaining_viable_indices, interval_length - 1) - remaining_viable_indices
    remaining_viable_indices <- remaining_viable_indices[!(is.na(check) | check >= interval_length)]
    if(length(remaining_viable_indices) > 0){
      next_sample <- sample(remaining_viable_indices, 1)
      next_sample <- next_sample : (next_sample + interval_length - 1)
      sampled_indices <- c(sampled_indices, next_sample)
      times <- times + 1
    } else{
      print("Ran out of nucleotides to sample")
      times <- size
    }
  }
  return(sampled_indices)
}

```

# Single simulation of mutation effects over time {.tabset .tabset-fade}

```{r single_sim_params, cache = T} 

#=====================================================================
# Mutation parameter selection. 
#=====================================================================
set.seed(0)

parent_dna <- beta_seq[[2]]

intervals <- 2
num_mutations <- seq(0, 76, by = intervals)

```

```{r single_sim, cache = T}

# Select mutation locations

mutation_locations <- c()
for(i in seq_along(num_mutations)[-1]){
  new_locations <- sample(setdiff(1:nchar(parent_dna), mutation_locations), intervals)
  mutation_locations <- c(mutation_locations, c(new_locations))
}

agg_sub_fas <- c(`Substitutions = 0` = parent_dna)
agg_del_fas <- c(`Deletions = 0` = parent_dna)

for(i in seq_along(num_mutations)[-1]){
  # Deletion mutations
  previous_del <- str_split(agg_del_fas[i - 1], "")[[1]]
  del_seq <- previous_del
  del_seq[mutation_locations[(1:intervals) + (i - 2) * intervals]] <- "-"
  agg_del_fas <- c(agg_del_fas, paste(del_seq, collapse = ""))
  names(agg_del_fas)[i] <- paste("Deletions =", num_mutations[i])
  
  # Substitution mutations
  previous_sub <- str_split(agg_sub_fas[i - 1], "")[[1]]
  sub_seq <- previous_sub
  sub_seq[mutation_locations[(1:intervals) + (i - 2) * intervals]] <- 
    mtte.V(previous_sub[mutation_locations[(1:intervals) + (i - 2) * intervals]])
  agg_sub_fas <- c(agg_sub_fas, paste(sub_seq, collapse = ""))
  names(agg_sub_fas)[i] <- paste("Substitutions =", num_mutations[i])
}

agg_fas <- c(agg_sub_fas[-1], gsub("-","",agg_del_fas)[-1])

all_mutations <- c(`Parent` = parent_dna, agg_fas)

```

## Clustal Omega + P-distance results

```{r clustal_p_1, dpi = 300}
#=====================================================================
# Mutation aggregation effects under Clustal Omega
#=====================================================================

clustal_omega <- function(dna_seq, outgroup = NULL){
  msa(dna_seq, type = "dna", method = "ClustalOmega", order = "input") |> 
    msaConvert(type = "ape::DNAbin") |> ape::dist.gene() 
}

clustal_output <- 
  msa(all_mutations, type = "dna", method = "ClustalOmega") |> 
  msaConvert(type = "ape::DNAbin") |> 
  ape::dist.gene() |> as.matrix() |> melt() |>
  filter(Var1 == "Parent" & Var2 != "Parent") |> 
  mutate(
    `Mutation count` = as.numeric(gsub("(Substitutions|Deletions) = ", "", Var2)),
    `Mutation percent` = `Mutation count`/nchar(parent_dna),
    `Mutation type` = gsub(" = [0-9]*", "", Var2)
  ) 

clustal_substitutions <- clustal_output |> filter(`Mutation type` == "Substitutions") 
clustal_deletions <- clustal_output |> filter(`Mutation type` == "Deletions") 

# Figure 
# Plots of the distance from the parent sequence as a function of the 
# percent of DNA that is mutated. 
clustal_output |> 
  ggplot(aes(x=`Mutation percent`, y = value,col = `Mutation type`, pch = `Mutation type`)) + 
  geom_point() + 
  geom_line(stat = "smooth", method="loess",
            method.args = list(degree = 1), se = F, alpha = .25, lwd = 2, span = .5) +
  theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
  ylab("Distance") + theme(legend.position = "bottom")

# Figure 
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  clustal_substitutions, clustal_deletions, 
  by = c("Var1", "Mutation count", "Mutation percent"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .75, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  scale_color_continuous(low = "blue", high = "orange")

```
## CGR shape signature distance results

```{r cgr_ss_1, dpi = 300, cache = T}

all_mut_cg <- lapply(all_mutations, seq_to_cgr) 

fracs <- seq(0.05, 1, by = .05)

cgr_output <- 
  lapply(
    fracs, 
    function(x) 
      cgr_distance(all_mut_cg, frac = x) |> melt() |> 
      filter(Var1 == "Parent" & Var2 != "Parent") |> 
      mutate(frac = x)
  ) |> 
  (\(x) do.call("rbind", x) )() |> 
  mutate(
    `Mutation count` = as.numeric(gsub("(Substitutions|Deletions) = ", "", Var2)),
    `Mutation percent` = `Mutation count`/nchar(parent_dna),
    `Mutation type` = gsub(" = [0-9]*", "", Var2)
  ) 


cgr_substitutions <- cgr_output |> filter(`Mutation type` == "Substitutions") 
cgr_deletions <- cgr_output |> filter(`Mutation type` == "Deletions") 

# Figure 
# Plots of the distance from the parent sequence as a function of the 
# percent of DNA that is mutated. 
cgr_output |> 
  ggplot(aes(x=`Mutation percent`, y = value,col = `Mutation type`, pch = `Mutation type`)) + 
  geom_point() + 
  geom_line(stat = "smooth", method="loess",
            method.args = list(degree = 1), se = F, alpha = .25, lwd = 2, span = .5) +
  theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
  facet_wrap(~frac) +
  ylab("Distance") + theme(legend.position = "bottom")

# Figure 
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  cgr_substitutions, cgr_deletions, 
  by = c("Var1", "Mutation count", "Mutation percent", "frac"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .75, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  facet_wrap(~frac) + 
  scale_color_continuous(low = "blue", high = "orange")


```


```{r cgr2_ss_1, dpi = 300, cache = T}

all_mut_cg <- lapply(all_mutations, seq_to_cgr) 

fracs <- seq(0.05, 1, by = .05)

cgr_output <- 
  lapply(
    fracs, 
    function(x) 
      cgr_distance2(all_mut_cg, frac = x) |> melt() |> 
      filter(Var1 == "Parent" & Var2 != "Parent") |> 
      mutate(frac = x)
  ) |> 
  (\(x) do.call("rbind", x) )() |> 
  mutate(
    `Mutation count` = as.numeric(gsub("(Substitutions|Deletions) = ", "", Var2)),
    `Mutation percent` = `Mutation count`/nchar(parent_dna),
    `Mutation type` = gsub(" = [0-9]*", "", Var2)
  ) 


cgr_substitutions <- cgr_output |> filter(`Mutation type` == "Substitutions") 
cgr_deletions <- cgr_output |> filter(`Mutation type` == "Deletions") 

# Figure 
# Plots of the distance from the parent sequence as a function of the 
# percent of DNA that is mutated. 
cgr_output |> 
  ggplot(aes(x=`Mutation percent`, y = value,col = `Mutation type`, pch = `Mutation type`)) + 
  geom_point() + 
  geom_line(stat = "smooth", method="loess",
            method.args = list(degree = 1), se = F, alpha = .25, lwd = 2, span = .5) +
  theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
  facet_wrap(~frac) +
  ylab("Distance") + theme(legend.position = "bottom")

# Figure 
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  cgr_substitutions, cgr_deletions, 
  by = c("Var1", "Mutation count", "Mutation percent", "frac"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .75, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  facet_wrap(~frac) + 
  scale_color_continuous(low = "blue", high = "orange")


```

## CGR volume intersection results 

```{r cgr_vol_int_1, dpi = 300, cache = T}

#=====================================================================
# Mutation aggregation effects under volume intersection method
#=====================================================================

set.seed(0)

bandwidth_options <- 
  c(seq(0.0001, 0.0009, by = 0.0001),
    seq(0.001, 0.009, by = 0.001),
    seq(0.01, 0.1, by = 0.01))

volume_results <- 
  lapply(
    bandwidth_options, 
    function(x){ 
      volume_intersection_tanimoto(all_mutations, x)
    }
  )

volume_results_df <- 
  lapply(
    seq_along(bandwidth_options), 
    function(x){
      melt(volume_results[x], value.name = "tanimoto") |> 
        filter(Var2 == "Parent" & Var1 != "Parent") |> 
        mutate(
          bandwidth_value = bandwidth_options[x],
          `Mutation type` =  gsub(" = [0-9]*", "", Var1),
          `Mutation count` = as.numeric(gsub("(Substitutions|Deletions) = ","", Var1)),
          `Mutation percent` = `Mutation count`/nchar(parent_dna)
        )
    }
  ) 

volume_results_df <- do.call(rbind, volume_results_df)

sub_vol <- volume_results_df |> filter(`Mutation type` == "Substitutions")
del_vol <- volume_results_df |> filter(`Mutation type` == "Deletions")

# Figure
# Distance from parent sequence as a function of percent of DNA that is mutated 
rbind(sub_vol, del_vol) |>   
  ggplot() + 
  geom_point(aes(x=`Mutation percent`, y = 1-tanimoto, col = bandwidth_value)) + 
  facet_wrap(~`Mutation type`) +
  scale_color_continuous("Bandwidth", low = "blue", high = "orange", trans = "log") +
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  theme_minimal() + scale_x_log10() + 
  ylab("Distance") 


# Figure
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  sub_vol, del_vol, 
  by = c("Mutation count", "Mutation percent", "bandwidth_value"), 
  suffix = c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=1-tanimoto.S, y=1-tanimoto.D, col = `Mutation percent`), alpha = .5) + 
  scale_color_continuous("Mutation\npercent", low = "blue", high = "orange") + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty =2) +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation")

# Figure
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by bandwidth
full_join(
  sub_vol, del_vol, 
  by = c("Mutation count", "Mutation percent", "bandwidth_value"), 
  suffix = c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=1-tanimoto.S, y=1-tanimoto.D, col = bandwidth_value), alpha = .5) + 
  scale_color_continuous("Bandwidth", low = "blue", high = "orange", trans = "log") + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty =2) +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation")

```

# Many simulations of mutation effects over time {.tabset .tabset-fade}

```{r multi_sim_params, cache = T}

#=====================================================================
# Mutation parameter selection. 
#=====================================================================

set.seed(0)

orig_seq <- str_split(beta_seq[[2]], "")[[1]]

num_mutations <- seq(1, 76, by = 1)

nsims <- 100

```

```{r multi_sim, cache = T}

simulations <- vector(mode = "list", length = nsims)
for(s in 1:nsims){
  i_len <- 1
  
  # Lists to store each generation
  del_line <- sub_line <- ins_line <- dup_line <- 
    vector(length = length(num_mutations))
  del_seq <- sub_seq <- ins_seq <- orig_seq 
  
  mutation_locations <- sample_interval(1:length(orig_seq), last(num_mutations), i_len)
 
  # Some last generation sequences
  sub_line.last <- orig_seq
  sub_line.last[mutation_locations] <- mtte(sub_seq[mutation_locations])
  
  ins_line.last <- insert_at(
    orig_seq, 
    mutation_locations[seq(1, length(mutation_locations), by = i_len)], 
    lapply(seq_along(num_mutations), function(x) sample(c("A", "C", "G", "T"), i_len, replace = T))
  )
  full_ins_helper <- insert_at(
    orig_seq, 
    mutation_locations[seq(1, length(mutation_locations), by = i_len)], 
    lapply(1:last(num_mutations), function(x) rep(x, each = i_len))
  )
  
  dup_line.last <- insert_at(
    orig_seq, 
    mutation_locations[seq(1, length(mutation_locations), by = i_len)], 
    orig_seq[mutation_locations[seq(1, length(mutation_locations), by = i_len)]] |> as.list()
  )
  
  for(i in seq_along(num_mutations)){
    # Deletion mutations
    del_seq[mutation_locations[1:(i_len * num_mutations[i])]] <- "-"
    del_line[i] <- paste(del_seq, collapse = "")
    names(del_line)[i] <- paste("Deletions =", num_mutations[i], "; Length =", i_len, "; Simulation", s)
    
    # Insertion mutations
    ins_seq <- ins_line.last[full_ins_helper %in% c("A", "C", "G", "T", 1:(num_mutations[i]))]
    ins_line[i] <- paste(ins_seq, collapse = "")
    names(ins_line)[i] <- paste("Insertions =", num_mutations[i], "; Length =", i_len, "; Simulation", s)
    
    # Duplication mutations
    dup_seq <- dup_line.last[full_ins_helper %in% c("A", "C", "G", "T", 1:(num_mutations[i]))]
    dup_line[i] <- paste(dup_seq, collapse = "")
    names(dup_line)[i] <- paste("Duplications =", num_mutations[i], "; Length =", i_len, "; Simulation", s)
    
    # Substitution mutations
    sub_seq[mutation_locations[1:(i_len * num_mutations[i])]] <- sub_line.last[mutation_locations[1:(i_len * num_mutations[i])]]
    sub_line[i] <- paste(sub_seq, collapse = "")
    names(sub_line)[i] <- paste("Substitutions =", num_mutations[i], "; Length =", i_len, "; Simulation", s)
  }
  
  simulations[[s]] <- 
    c(`Parent` = paste(orig_seq, collapse = ""), sub_line, gsub("-","",del_line), ins_line, dup_line)
}

```

## Clustal Omega + P-distance results 

```{r clustal_p_n, dpi = 300, cache = T}

clustal_output <- 
  lapply(
    simulations,
    function(x){
      msa(x, type = "dna", method = "ClustalOmega") |> 
        msaConvert(type = "ape::DNAbin") |> 
        ape::dist.gene() |> as.matrix() |> melt() |>
        filter(Var1 == "Parent" & Var2 != "Parent") |> 
        mutate(
          `Mutation count` = as.numeric(sapply(str_split(Var2, " "), function(x) x[3])),
          `Mutation percent` = `Mutation count`/length(orig_seq),
          `Mutation type` = sapply(str_split(Var2, " "), function(x) x[1]),
          `Simulation` =  sapply(str_split(Var2, " "), function(x) x[10])
        )
    }
  )


do.call("rbind", clustal_output) |> 
    ggplot(aes(x=`Mutation percent`, y = value, col = `Mutation type`, pch = `Mutation type`)) + 
    geom_point(alpha = .1) + 
    geom_line(stat = "smooth", method="loess",
              method.args = list(degree = 1), se = F, alpha = .5, lwd = 2, span = .5) +
    theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + facet_wrap(~`Mutation type`) + 
    ylab("Distance") + theme(legend.position = "bottom")


full_join(
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Substitutions"),
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Deletions"), 
  by = c("Var1", "Mutation count", "Mutation percent", "Simulation"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .15, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  scale_color_continuous(low = "blue", high = "orange")

full_join(
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Insertions"),
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Deletions"), 
  by = c("Var1", "Mutation count", "Mutation percent", "Simulation"), 
  suffix=c(".I", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.I, y=value.D, col = `Mutation percent`), alpha = .15, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to insertion mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  scale_color_continuous(low = "blue", high = "orange")

full_join(
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Insertions"),
  do.call("rbind", clustal_output) |> filter(`Mutation type` == "Substitutions"), 
  by = c("Var1", "Mutation count", "Mutation percent", "Simulation"), 
  suffix=c(".I", ".S")
) |>
  ggplot() + 
  geom_point(aes(x=value.I, y=value.S, col = `Mutation percent`), alpha = .15, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to insertion mutation") + 
  ylab("Distance from parent sequence\ndue to substitution mutation") +
  scale_color_continuous(low = "blue", high = "orange")

```
## CGR distance results


```{r cgr_ss_n, cache = T, eval = F}

# Can't run this until my functions are built into a package that can then be 
# exported to all worker nodes
# s0 <- proc.time()
# 
# cl <- makeCluster(4)
# coords <- as.matrix(coord1[, 1:3])
# clusterExport(
#   cl,
#   c("simulations", "cgr_distance", "seq_to_cgr", "coord1", "nsims", "coords"),
#   envir = environment()
# )
# 
# ## set up each worker.
# clusterEvalQ(cl, {library(tidyverse)})
# clusterEvalQ(cl, {library(reshape2)})
# clusterEvalQ(cl, {library(stringr)})
# clusterEvalQ(cl, {library(Rcpp)})
# 
# fracs <- seq(0.05, 1, by = .05)
# clusterExport(cl, c("fracs"), envir = environment())
# 
# cgr_output_list.p <- vector(mode = "list", length = length(fracs))
# for(f in seq_along(fracs)){
#   print(fracs[f])
#   clusterExport(cl, c("f"), envir = environment())
#   temp <- parLapply(
#     cl,
#     1:nsims,
#     function(i){
#       lapply(simulations[[i]], seq_to_cgr) |>
#         cgr_distance(frac = fracs[f]) |> melt() |>
#         filter(Var1 == "Parent" & Var2 != "Parent") |>
#         mutate(frac = fracs[f]) |>
#         mutate(
#           `Mutation count` = as.numeric(sapply(str_split(Var2, " "), function(x) x[3])),
#           `Mutation percent` = `Mutation count`/length(orig_seq),
#           `Mutation type` = sapply(str_split(Var2, " "), function(x) x[1]),
#           `Simulation` =  sapply(str_split(Var2, " "), function(x) x[10])
#         )
#     }
#   )
#   cgr_output_list.p[[f]] <- temp
# }
# 
# stopCluster(cl)
# e0 <- proc.time()


fracs <- seq(0.05, 1, by = .05)
cgr_output_list <- vector(mode = "list", length = length(fracs) * nsims)
s1 <- proc.time()
counter <- 1
for(f in seq_along(fracs)){
  print(fracs[f])
  
  for(i in 1:nsims){
    print(i)
    temp <- 
      lapply(simulations[[i]], seq_to_cgr) |> 
      cgr_distance(frac = fracs[f]) |> melt() |> 
      filter(Var1 == "Parent" & Var2 != "Parent") |> 
      mutate(frac = fracs[f]) |> 
      mutate(
        `Mutation count` = as.numeric(sapply(str_split(Var2, " "), function(x) x[3])),
        `Mutation percent` = `Mutation count`/length(orig_seq),
        `Mutation type` = sapply(str_split(Var2, " "), function(x) x[1]),
        `Simulation` =  sapply(str_split(Var2, " "), function(x) x[10])
      ) 
    cgr_output_list[[counter]] <- temp
    counter <- counter + 1
  }
}
e1 <- proc.time()

cgr_output_list.rbind <- do.call("rbind", cgr_output_list)

cgr_substitutions <- cgr_output_list.rbind |> filter(`Mutation type` == "Substitutions") 
cgr_deletions <- cgr_output_list.rbind |> filter(`Mutation type` == "Deletions") 

# Figure 
# Plots of the distance from the parent sequence as a function of the 
# percent of DNA that is mutated. 
cgr_output_list.rbind |> 
  ggplot(aes(x=`Mutation percent`, y = value,col = `Mutation type`, pch = `Mutation type`)) + 
  geom_point(alpha = .15) + 
  geom_line(stat = "smooth", method="loess",
            method.args = list(degree = 1), se = F, alpha = .25, lwd = 2, span = .75) +
  theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
  facet_wrap(~frac) +
  ylab("Distance") + theme(legend.position = "bottom")

# Figure 
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  cgr_substitutions, cgr_deletions, 
  by = c("Var1", "Mutation count", "Mutation percent", "frac", "Simulation"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .75, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  facet_wrap(~frac) + 
  scale_color_continuous(low = "blue", high = "orange")

```

```{r}


fracs <- seq(0.05, 1, by = .05)
cgr2_output_list <- vector(mode = "list", length = length(fracs) * nsims)
s1 <- proc.time()
counter <- 1
for(f in seq_along(fracs)){
  print(fracs[f])
  
  for(i in 1:nsims){
    print(i)
    temp <- 
      lapply(simulations[[i]], seq_to_cgr) |> 
      cgr_distance2(frac = fracs[f]) |> melt() |> 
      filter(Var1 == "Parent" & Var2 != "Parent") |> 
      mutate(frac = fracs[f]) |> 
      mutate(
        `Mutation count` = as.numeric(sapply(str_split(Var2, " "), function(x) x[3])),
        `Mutation percent` = `Mutation count`/length(orig_seq),
        `Mutation type` = sapply(str_split(Var2, " "), function(x) x[1]),
        `Simulation` =  sapply(str_split(Var2, " "), function(x) x[10])
      ) 
    cgr2_output_list[[counter]] <- temp
    counter <- counter + 1
  }
}
e1 <- proc.time()

cgr2_output_list.rbind <- do.call("rbind", cgr2_output_list)

cgr2_substitutions <- cgr_output_list.rbind |> filter(`Mutation type` == "Substitutions") 
cgr2_deletions <- cgr_output_list.rbind |> filter(`Mutation type` == "Deletions") 

# Figure 
# Plots of the distance from the parent sequence as a function of the 
# percent of DNA that is mutated. 
cgr2_output_list.rbind |> 
  ggplot(aes(x=`Mutation percent`, y = value,col = `Mutation type`, pch = `Mutation type`)) + 
  geom_point(alpha = .15) + 
  geom_line(stat = "smooth", method="loess",
            method.args = list(degree = 1), se = F, alpha = .25, lwd = 2, span = .75) +
  theme_minimal() + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
  facet_wrap(~frac) +
  ylab("Distance") + theme(legend.position = "bottom")

# Figure 
# Distance from parent sequence due to deletion mutation v 
# distance from parent sequence due to substitution mutation, 
# colored by proportion of sequence that has been mutated.
full_join(
  cgr2_substitutions, cgr2_deletions, 
  by = c("Var1", "Mutation count", "Mutation percent", "frac", "Simulation"), 
  suffix=c(".S", ".D")
) |>
  ggplot() + 
  geom_point(aes(x=value.S, y=value.D, col = `Mutation percent`), alpha = .75, size = 3) + 
  theme_minimal() +  
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +  
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  xlab("Distance from parent sequence\ndue to substitution mutation") + 
  ylab("Distance from parent sequence\ndue to deletion mutation") +
  facet_wrap(~frac) + 
  scale_color_continuous(low = "blue", high = "orange")

```
```